# Generated by Django 4.2.10 on 2025-04-23 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import factuai.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvoiceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=factuai.models.invoice_file_path)),
                ("file_type", models.CharField(max_length=10)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.IntegerField()),
                (
                    "image",
                    models.ImageField(upload_to=factuai.models.invoice_page_path),
                ),
                ("ocr_text", models.TextField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="factuai.invoicedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["invoice", "page_number"],
                "unique_together": {("invoice", "page_number")},
            },
        ),
        migrations.CreateModel(
            name="ExtractedInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("invoice_number", models.CharField(max_length=100)),
                ("invoice_date", models.DateField()),
                ("raw_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_data",
                        to="factuai.invoicepage",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date", "company"],
            },
        ),
    ]
