# Generated by Django 5.2 on 2025-04-25 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factuai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("invoice_number", models.CharField(max_length=100)),
                ("invoice_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-invoice_date", "company"],
                "unique_together": {("company", "invoice_number")},
            },
        ),
        migrations.AddField(
            model_name="extractedinvoice",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_invoices",
                to="factuai.invoicegroup",
            ),
        ),
    ]
