# Generated by Django 5.1.6 on 2025-05-15 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factuai", "0002_invoicegroup_extractedinvoice_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre oficial de la empresa",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "nombre_normalizado",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre normalizado para búsquedas (sin acentos, minúsculas)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "nombres_detectados",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de nombres previamente detectados por OCR",
                    ),
                ),
                ("nif", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="invoicegroup",
            name="necesita_revision",
            field=models.BooleanField(
                default=False,
                help_text="Indica si esta factura necesita revisión manual de la empresa",
            ),
        ),
        migrations.AlterField(
            model_name="invoicegroup",
            name="company",
            field=models.CharField(
                help_text="Nombre detectado originalmente (para compatibilidad)",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoicegroup",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="invoicegroup",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas",
                to="factuai.empresa",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoicegroup",
            unique_together={("empresa", "invoice_number")},
        ),
    ]
