# Generated by Django 5.2 on 2025-04-23 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ocr_id",
                    models.CharField(
                        help_text="Identificador único del OCR",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("text_content", models.TextField(help_text="Contenido del texto OCR")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Empresa extraída del OCR",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de factura extraído del OCR",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "invoice_date",
                    models.CharField(
                        blank=True,
                        help_text="Fecha de factura extraída del OCR",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "raw_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON completo extraído del modelo",
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "ocr_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_data",
                        to="extractor.ocrrequest",
                    ),
                ),
            ],
        ),
    ]
