# Generated by Django 5.2 on 2025-04-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
